services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    container_name: graphql_api
    volumes:
      - ./app.py:/app/app.py
      - ./server:/app/server
    ports:
      - '5000:5000'
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
